### ISSUE TITLE
InputCenterLayer？

### ISSUE THREAD

**Issue by zhangdong1992** [Hadisalman/smoothing-adversarial#1]
The difference between InputCenterLayer and NormalizeLayer is simply that InputCenterLayer is not divided by the sds. What are the benefits of doing this?

**Comment by Hadisalman** [comment]
Apologies for the late reply, for some reason I didn't notice the issue previously. We didn't find any benefits from doing either. We experimented with both, and eventually we sticked with one. They both give very similar results.
