### ISSUE TITLE
Download the archive of pretrained model failed

### ISSUE THREAD

**Issue by IDKiro** [Hadisalman/smoothing-adversarial#4]
The archive size too big, and it's hard for me to download the archive since I will be blocked by Google when downloading the large file (when the file has been almost downloaded).
So I want to get archives of the single models. It will help me a lot.
Of course, it depends if you are not busy. I apologize for my reckless request.

**Comment by Hadisalman** [comment]
@IDKiro I assume that you are able to download the pretrained models. Please let me know if you need any further help :)
