### ISSUE TITLE
Cannot download your trained models

### ISSUE THREAD

**Issue by cchen-vis** [Hadisalman/smoothing-adversarial#7]
Hi,

In the section **Getting Started**, I cannot download your trained models. Could you please update your cloud files?

Best,

Chen

**Comment by Hadisalman** [comment]
Hi @ShanghaitechChen , I am not sure why you are not able to download the models. They should be accessible fine through the link the in the getting started section https://drive.google.com/u/0/uc?id=1GH7OeKUzOGiouKhendC-501pLYNRvU8c&export=download I just tried it and it works fine. Please let me know what exactly you are getting.

**Comment by cchen-vis** [comment]
Oh I see, it is so big that I thought there is something wrong.
If it is convenient, could you send me your trained model on cifar10 under PGD attack with parameters: --noise_sd 1.00 --lr_step_size 50 --epochs 150 --adv-training --num-steps 10 --epsilon 512 --train-multi-noise --num-noise-vec 2?

**Comment by Hadisalman** [comment]
I am so sorry I missed this comment :( Please let me know if you still need anything.
