### ISSUE TITLE
train_pgd.py noise parameter

### ISSUE THREAD

**Issue by sudipansaha** [Hadisalman/smoothing-adversarial#9]
The command for running train_pgd.py is given as:
python code/train_pgd.py cifar10 cifar_resnet110 model_output_dir --batch 256 --noise 0.12 --gpu 0 --lr_step_size 50 --epochs 150 --adv-training --attack PGD --num-steps 10 --epsilon 64 --train-multi-noise --num-noise-vec 2 --warmup 10

One of the parameters in the above command is noise. However, I could not find noise in arguments list in train_pgd.py. There is a noise_sd. Is it same as noise in the above command?

**Comment by Hadisalman** [comment]
Hi @sudipansaha!

Yes exactly, it is the same argument. Thanks for catching this!
